version: '3.9'

services:

  client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: example_name_client
    ports: 
     - '3000:3000'
    volumes:
      - /src
      - /app/node_modules
    stdin_open: true
    tty: true

